FROM node:14

#Create Work Directory
WORKDIR /usr/src/app


#Copy package.json And package-lock.json
COPY package*.json ./

RUN npm install

#Copy Source Code Inside Docker
COPY . .

EXPOSE 3000

CMD ["npm","start"]